baseurl = "https://jefflund.website"
languageCode = "en-us"
title = "Jeff Lund's Website"
copyright = "&copy; Jeffrey Lund 2017"

[[menu.social]]
name = "github"
url = "https://github.com/jefflund"
weight = 1
