baseurl = "https://jefflund.website"
languageCode = "en-us"
title = "Jeff Lund's Website"
copyright = "&copy; Jeffrey Lund 2017"
enableRobotsTXT = true
enableEmoji = true

[params]
coverphoto = "/img/cover.jpg"

[[menu.navbar]]
name = "Home"
url = "/"
weight = 1

[[menu.navbar]]
name = "About"
url = "/about"
weight = 2

[[menu.navbar]]
name = "Publications"
url = "/publications"
weight = 3

[[menu.navbar]]
name = "Resume"
url = "/resume.pdf"
weight = 4

[[menu.social]]
name = "github"
url = "https://github.com/jefflund"
weight = 1

[[menu.social]]
name = "twitter"
url = "https://twitter.com/jefflund_"
weight = 3

[[menu.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/jeffrey-lund-3b488929"
weight = 2
